SELECT * FROM Carga

EXEC CARREGAR_CLIENTES
EXEC CARREGAR_PRODUTOS
EXEC CARREGAR_PEDIDOS
EXEC CARREGAR_iTENS_PEDIDOS
EXEC MOVIMENTAR_ESTOQUE

SELECT * FROM Cliente
SELECT * FROM Produto 
SELECT * FROM Pedido
SELECT * FROM Itens_Pedidos
SELECT * FROM Movimentação_Estoque
SELECT * FROM Compras

DELETE FROM Carga
DELETE FROM Itens_Pedidos 
DELETE FROM Compras 
DELETE FROM Movimentação_Estoque 
DELETE FROM Produto 
DELETE FROM Pedido 
DELETE FROM Cliente